# Specification of other config files and output location
it_data_config_yml: /path/to/ProCyon/examples/evaluation/dataset_config.yml
models_config_yml: /path/to/ProCyon/examples/evaluation/model_config.yml
output_dir: /path/to/output

# Point to checkpoint of any ProCyon model being used to ensure consistency of data loading
# with how the model was trained.
model_args_from_checkpoint: /path/to/model_checkpoints/ProCyon-Split
data_args_from_checkpoint: /path/to/model_checkpoints/ProCyon-Split

# Arguments specifying how different dataset splits should be handled.
filter_training_pairs: True
separate_splits: True
keep_splits_union: False

# Arguments for controlling how retrieval evaluation is performed
retrieval_eval_all_aaseqs: True
retrieval_top_k_vals: [10, 20, 100]
retrieval_balanced_metrics_num_samples: 5
retrieval_balanced_metrics_neg_per_pos: 10
retrieval_use_cached_target_embeddings: True

# Additional arguments for more efficient runs.
batch_size: 4
use_cached_results: True
